apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: vehicle-rental-staging
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: mohammed761/backend-auth-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: vehicle-rental-config
                  key: NODE_ENV
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: vehicle-rental-config
                  key: MONGODB_URI_AUTH
            - name: JWT_SECRET
              value: "staging-jwt-secret"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: vehicle-rental-staging
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
