apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-rental-config
  namespace: vehicle-rental-staging
data:
  NODE_ENV: "staging"
  MONGODB_URI_AUTH: "mongodb://mongodb-service:27017/admin_auth_staging"
  MONGODB_URI_VEHICLE: "mongodb://mongodb-service:27017/vehicle_db_staging"
  MONGODB_URI_LOG: "mongodb://mongodb-service:27017/logs_db_staging"
  REDIS_URI: "redis://redis-service:6379"
  KAFKA_BROKERS: "kafka-service:9092"
