apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  namespace: vehicle-rental-staging
  labels:
    app: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
        - name: log-service
          image: mohammed761/backend-log-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: vehicle-rental-config
                  key: NODE_ENV
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: vehicle-rental-config
                  key: MONGODB_URI_LOG
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: vehicle-rental-staging
spec:
  selector:
    app: log-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
