apiVersion: v1
kind: ConfigMap
metadata:
  name: vehicle-rental-config
  namespace: vehicle-rental-prod
data:
  NODE_ENV: "production"
  MONGODB_URI_AUTH: "mongodb://mongodb-service:27017/admin_auth"
  MONGODB_URI_VEHICLE: "mongodb://mongodb-service:27017/vehicle_db"
  MONGODB_URI_LOG: "mongodb://mongodb-service:27017/logs_db"
  REDIS_URI: "redis://redis-service:6379"
  KAFKA_BROKERS: "kafka-service:9092"
