apiVersion: v1
kind: Secret
metadata:
  name: vehicle-rental-secrets
  namespace: vehicle-rental-prod
type: Opaque
data:
  JWT_SECRET: <base64-encoded-jwt-secret>
  MONGODB_PASSWORD: <base64-encoded-mongodb-password>
